version: '3.3'
services:
  ### PHP-FPM Container
  php-fpm:
    build: ./build/php-fpm
    volumes:
      - ./../src:/var/www
    networks:
      - mutilsite
    expose:
      - "9000"
    links:
      - mysql
      - redis
  
  ### NGINX Container
  nginx:
    build: ./build/nginx
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./../src:/var/www
    networks:
      - mutilsite
    ports:
      - "80:80"
    links:
      - php-fpm

  ### MySQL Container
  mysql:
    container_name: mysql-multi
    build: ./build/mysql
    volumes:
      - ${DB_DIR}:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - mutilsite
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    ports:
      - "3306:3306"
      
  ### Redis Container
  redis:
    image: redis
    networks:
      - mutilsite
    expose:
        - "6379"
  
  ### Workspace Utilities Container
  workspace:
    build: ./build/workspace
    volumes:
      - ./../src:/var/www
    links:
      - mysql
      - redis
    tty: true
    networks:
      - mutilsite

networks:
  mutilsite:

volumes:
  workspace:
